-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN     "budgetResetAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "monthlyTokenBudget" INTEGER NOT NULL DEFAULT 2000000,
ADD COLUMN     "monthlyTokensUsed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "trialEndsAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "isSysAdmin" BOOLEAN NOT NULL DEFAULT false;
